name: CI
on:
  push:
    branches:
      - Toan191A010141

  pull_request:
    branches:
      - Toan191A010141

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:    
    - name: Display notification 1
      run: echo "Hello Duc!"
    
    - name: Display notification 2
      run: echo "Hello Thoai!"
    
    - name: Display notification 3
      run: echo "Hello Toan!"